name: ODASA analysis

on: [push, milestone]

jobs:
  analysis_job:
    runs-on: ubuntu-latest
    name: Analysis job
    steps:
    - uses: actions/checkout@v1
    - name: Setup source
      run: |
        mkdir "$GITHUB_WORKSPACE/source"
        cp -r src "$GITHUB_WORKSPACE/source"
        cd "$GITHUB_WORKSPACE/source"
        pwd
    - name: Perform analysis
      id: analysis
      uses: joshhale/odasa-action@master
      with:
        language: javascript
        odasa: ${{ secrets.ODASA_URL }}
        license: ${{ secrets.ODASA_LICENSE }}
    - name: List files
      run: |
        ls -la
        ls -la ${{ steps.analysis.outputs.snapshot }}
    - name: Upload snapshot
      uses: actions/upload-artifact@master
      with:
        name: snapshot
        path: ${{ steps.analysis.outputs.snapshot }}
